# Generated by Django 4.2.30 on 2026-09-25 03:56

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(help_text='Nota de 0 a 100')),
                ('fecha_calificacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'calificaciones',
                'ordering': ['-fecha_calificacion'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, default='Ciencias de la Computación', max_length=150)),
                ('titulo_academico', models.CharField(default='Profesor Titular', max_length=150)),
                ('biografia', models.TextField(blank=True, default='Docente de materias de computación, desarrollo de software y sistemas.')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#1E3A8A', max_length=30)),
                ('icono', models.CharField(default='database', max_length=50)),
                ('imagen_url', models.CharField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='core.docente')),
            ],
            options={
                'db_table': 'espacios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera_o_area', models.CharField(default='Ingeniería de Sistemas e Informática', max_length=150)),
                ('biografia', models.TextField(blank=True, default='Estudiante enfocado en el desarrollo de software y bases de datos.')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('indicaciones', models.TextField(blank=True)),
                ('puntaje_maximo', models.IntegerField(default=100)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_limite', models.DateTimeField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('FINALIZADA', 'Finalizada')], default='PUBLICADA', max_length=20)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.docente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.espacio')),
            ],
            options={
                'db_table': 'tareas',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Retroalimentación cualitativa y sugerencias de mejora')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('calificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentacion', to='core.calificacion')),
            ],
            options={
                'db_table': 'retroalimentaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField(default=0.0)),
                ('tareas_entregadas', models.IntegerField(default=0)),
                ('tareas_pendientes', models.IntegerField(default=0)),
                ('tareas_calificadas', models.IntegerField(default=0)),
                ('tareas_vencidas', models.IntegerField(default=0)),
                ('porcentaje_cumplimiento', models.FloatField(default=0.0)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='core.estudiante')),
            ],
            options={
                'db_table': 'progreso_academico',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVA_TAREA', 'Nueva Tarea'), ('PROXIMA_VENCER', 'Próxima a Vencer'), ('VENCIDA', 'Tarea Vencida'), ('CALIFICADA', 'Tarea Calificada'), ('RETROALIMENTACION', 'Nueva Retroalimentación'), ('INVITACION_ESPACIO', 'Espacio Académico'), ('ENTREGA_CONFIRMADA', 'Entrega Confirmada')], default='NUEVA_TAREA', max_length=30)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
                ('espacio_id', models.IntegerField(blank=True, null=True)),
                ('tarea_id', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('PDF', 'Documento PDF'), ('DOCUMENTO', 'Documento Word/Texto'), ('PRESENTACION', 'Presentación PPT'), ('HOJA_CALCULO', 'Hoja de Cálculo Excel'), ('ENLACE', 'Enlace Web'), ('CODIGO', 'Archivo de Código / Script')], default='PDF', max_length=30)),
                ('archivo_url', models.CharField(max_length=500)),
                ('tamano', models.CharField(default='1.2 MB', max_length=30)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='core.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo_url', models.CharField(blank=True, max_length=500)),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('archivo_tamano', models.CharField(blank=True, default='1.8 MB', max_length=30)),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios del estudiante para el docente')),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En proceso'), ('ENTREGADO', 'Entregada'), ('EN_REVISION', 'En revisión'), ('CALIFICADO', 'Calificada'), ('RETROALIMENTADA', 'Retroalimentada'), ('VENCIDA', 'Vencida'), ('ATRASADO', 'Entregada con retraso')], default='ENTREGADO', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.tarea')),
            ],
            options={
                'db_table': 'entregas',
                'ordering': ['-fecha_entrega'],
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
        migrations.AddField(
            model_name='calificacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='core.docente'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='entrega',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='core.entrega'),
        ),
        migrations.CreateModel(
            name='MiembroEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(default=django.utils.timezone.now)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='core.espacio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_inscritos', to='core.estudiante')),
            ],
            options={
                'db_table': 'miembros_espacio',
                'ordering': ['-fecha_union'],
                'unique_together': {('espacio', 'estudiante')},
            },
        ),
    ]
