# Generated by Django 4.2.28 on 2026-09-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, default='Ecuador', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('color', models.CharField(default='#1E3A8A', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'colegios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('paralelo', models.CharField(max_length=10)),
                ('nivel', models.CharField(blank=True, max_length=100)),
                ('anio_lectivo', models.CharField(default='2026-2027', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.colegio')),
            ],
            options={
                'db_table': 'cursos',
                'ordering': ['grado', 'paralelo'],
                'unique_together': {('colegio', 'grado', 'paralelo', 'anio_lectivo')},
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='entregas/'),
        ),
        migrations.AddField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='materiales/'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='docente',
            name='biografia',
            field=models.TextField(blank=True, default='Docente de materias de computacion.'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='especialidad',
            field=models.CharField(blank=True, default='Ciencias de la Computacion', max_length=150),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En proceso'), ('ENTREGADO', 'Entregada'), ('EN_REVISION', 'En revision'), ('CALIFICADO', 'Calificada'), ('RETROALIMENTADA', 'Retroalimentada'), ('VENCIDA', 'Vencida'), ('ATRASADO', 'Atrasado')], default='ENTREGADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='biografia',
            field=models.TextField(blank=True, default='Estudiante de sistemas.'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera_o_area',
            field=models.CharField(default='Ingenieria de Sistemas', max_length=150),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOCUMENTO', 'Word'), ('PRESENTACION', 'PPT'), ('HOJA_CALCULO', 'Excel'), ('ENLACE', 'Enlace'), ('IMAGEN', 'Imagen'), ('ZIP', 'ZIP')], default='PDF', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('NUEVA_TAREA', 'Nueva Tarea'), ('PROXIMA_VENCER', 'Proxima a Vencer'), ('VENCIDA', 'Vencida'), ('CALIFICADA', 'Calificada'), ('RETROALIMENTACION', 'Retroalimentacion'), ('INVITACION_ESPACIO', 'Espacio'), ('ENTREGA_CONFIRMADA', 'Entrega'), ('INVITACION_COLEGIO', 'Colegio')], default='NUEVA_TAREA', max_length=30),
        ),
        migrations.AlterField(
            model_name='retroalimentacion',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='material',
            table='materiales',
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje_total', models.IntegerField(default=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='core.docente')),
            ],
            options={
                'db_table': 'rubricas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('horas_semanales', models.IntegerField(default=2)),
                ('color', models.CharField(default='#0284C7', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.docente')),
            ],
            options={
                'db_table': 'materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('codigo_ru', models.CharField(blank=True, max_length=50)),
                ('codigo_invitacion', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.docente')),
            ],
            options={
                'db_table': 'invitaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_anterior', models.FloatField()),
                ('nota_nueva', models.FloatField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.calificacion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_calificaciones', to='core.docente')),
            ],
            options={
                'db_table': 'historial_calificaciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='CriterioRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje_maximo', models.IntegerField(default=20)),
                ('orden', models.IntegerField(default=0)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='core.rubrica')),
            ],
            options={
                'db_table': 'criterios_rubrica',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='espacio',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to='core.colegio'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to='core.curso'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to='core.materia'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='core.rubrica'),
        ),
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ru', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_inscritos', to='core.estudiante')),
            ],
            options={
                'db_table': 'estudiante_curso',
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='DocenteColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, default='Docente', max_length=100)),
                ('fecha_incorporacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='core.colegio')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colegios', to='core.docente')),
            ],
            options={
                'db_table': 'docente_colegio',
                'unique_together': {('docente', 'colegio')},
            },
        ),
    ]
