# Generated by Django 4.2.28 on 2026-09-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colegio_curso_entrega_archivo_material_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado')], default='ACTIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_codigo', to='core.espacio')),
            ],
            options={
                'db_table': 'invitaciones_espacio',
            },
        ),
    ]
