# Generated by Django 4.2.30 on 2026-09-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitacionespacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionespacio',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
