# Generated by Django 4.2.30 on 2026-09-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitacionespacio_fecha_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
