# Generated by Django 4.2.30 on 2026-09-28 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_badge_challenge_event_cointransaction_userchallenge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='challenge',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos_creados', to='core.docente'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='espacio',
            field=models.ForeignKey(blank=True, help_text='Si está vacío, el reto es global para todos los estudiantes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retos', to='core.espacio'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='challenge',
            name='meta',
            field=models.IntegerField(default=1, help_text='Número de veces que se debe completar la acción'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='tipo',
            field=models.CharField(choices=[('TAREAS', 'Entregar Tareas'), ('PUNTAJE', 'Obtener Puntaje'), ('ASISTENCIA', 'Asistencia'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
