# Generated by Django 4.2.30 on 2026-10-01 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_challenge_vinculado_espacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En proceso'), ('ENTREGADO', 'Entregada'), ('EN_REVISION', 'En revision'), ('CALIFICADO', 'Calificada'), ('RETROALIMENTADA', 'Retroalimentada'), ('DEVUELTA', 'Devuelta para corrección'), ('REENTREGADA', 'Reentregada'), ('VENCIDA', 'Vencida'), ('ATRASADO', 'Atrasado')], default='ENTREGADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('NUEVA_TAREA', 'Nueva Tarea'), ('PROXIMA_VENCER', 'Proxima a Vencer'), ('VENCIDA', 'Vencida'), ('CALIFICADA', 'Calificada'), ('RETROALIMENTACION', 'Retroalimentacion'), ('CORRECCION_SOLICITADA', 'Corrección Solicitada'), ('REENTREGA', 'Reentrega'), ('AVISO_NUEVO', 'Nuevo Aviso'), ('INVITACION_ESPACIO', 'Espacio'), ('ENTREGA_CONFIRMADA', 'Entrega'), ('INVITACION_COLEGIO', 'Colegio')], default='NUEVA_TAREA', max_length=30),
        ),
        migrations.CreateModel(
            name='VersionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.IntegerField(default=1)),
                ('archivo_url', models.CharField(blank=True, max_length=500)),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('archivo_tamano', models.CharField(blank=True, default='1.8 MB', max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='ENTREGADO', max_length=30)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='core.entrega')),
            ],
            options={
                'db_table': 'versiones_entrega',
                'ordering': ['-numero_version'],
            },
        ),
        migrations.CreateModel(
            name='RecursoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('DOCUMENTO', 'Documento'), ('PRESENTACION', 'Presentación'), ('ENLACE', 'Enlace'), ('VIDEO', 'Video'), ('GUIA', 'Guía de Estudio'), ('OTRO', 'Otro')], default='PDF', max_length=30)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos_espacio/')),
                ('archivo_url', models.CharField(blank=True, max_length=500)),
                ('enlace_url', models.CharField(blank=True, max_length=500)),
                ('tamano', models.CharField(blank=True, default='1.5 MB', max_length=30)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_creados', to='core.docente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.espacio')),
            ],
            options={
                'db_table': 'recursos_espacio',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('indicaciones', models.TextField(blank=True)),
                ('puntaje_maximo', models.IntegerField(default=100)),
                ('criterios_json', models.TextField(blank=True, default='[]')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_tarea', to='core.docente')),
            ],
            options={
                'db_table': 'plantillas_tarea',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AvisoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fijado', models.BooleanField(default=False)),
                ('importante', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='core.docente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='core.espacio')),
            ],
            options={
                'db_table': 'avisos_espacio',
                'ordering': ['-fijado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionFechaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nueva_fecha_limite', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensiones_otorgadas', to='core.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensiones_tarea', to='core.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensiones', to='core.tarea')),
            ],
            options={
                'db_table': 'extensiones_tarea',
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
    ]
